name: stormcat24/importer-source/sample
on:
  push:
    branches:
    - main
jobs:
  build:
    defaults:
      run:
        working-directory: . 
    runs-on: ubuntu-latest
    container:
      image: golang:1.17
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Wait for db
      run: dockerize -wait tcp://localhost:3306 -timeout 1m -wait-retry-interval 5s
    - name: restore_cache
      uses: actions/cache@v3
      with:
        key: go-mod-v4-{{ checksum "go.sum" }}
        restore-keys: go-mod-v4-{{ checksum "go.sum" }}
        path: "/go/pkg/mod"
    - name: Install Dependencies
      run: go mod download
    - name: Run tests
      run: |-
        mkdir -p /tmp/test-reports
        # comment out 4
        # gotestsum --junitfile /tmp/test-reports/unit-tests.xml
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: "/tmp/test-reports"
